version: '3.4'
services:
  pornreviews.pinkworld.com:
    image: docker-apache-php53_web
    restart: always
    ports:
      - 8084:80
    volumes:
      - /www/pornreviews.pinkworld.com:/var/www/html
  pinkworld.com:
    image: docker-apache-php53_web
    restart: always
    ports:
      - 8082:80
    volumes:
      - /www/pinkworld.com:/var/www/html
  partybuscharleston.com:
    image: docker-apache-php53_web
    restart: always
    ports:
      - 8083:80
    volumes:
      - /www/partybuscharleston.com:/var/www/html
